name: Production test
on:
  pull_request: # run on pull requests into the deployed branch (dev) and main
    branches:
      - dev
      - main

jobs:
  build:
    name: run lint and production build
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: running lint
        run: npm run lint
      - name: production build
        run: npm run build
