name: Production test
on:
  pull_request: # run only on created pull request on main
    branches: 
      - main
      
jobs:
  build:
    name: run lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: check out code 
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
      - name: install dependencies
        run: npm install
      - name: running lint
        run: npm run lint
      - name: run eslint
        run: npm run alltests