name: Pylint
# ---------------------------------------#
# ---------------------------------------#
# ---   PYLINTER - Github Actions   -----#
# ---------------------------------------#
# ---------------------------------------#
# Pylint for github actions. Runs seperate to superlinter

# Documentation and source:
# https://github.com/cclauss/GitHub-Action-for-pylint



on:
  push:
    paths:
      # Add specific files / filetypes here.
      # Use `**` to wildcard through multiply paths
      - "**.py"
    # [un]-comment the following line to toggle for push to master
    # branches-ignore: [master, main]

  This will only work when this workflow is on default branch
  TODO: Uncomment when merging
  pull_requests:
    branches: [dev, master, main]

jobs:
  build:
    name: Pylint
    # Works on most linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analyse Code with Pylint
      run: |
        pylint $(git ls-files '*.py')

      env:
        # may be worth changing this to master / main / dev in future
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # For pylint's settings
        PYTHON_PYLINT_CONFIG_FILE: .pylintrc
